# Generated by Django 4.1.3 on 2022-11-21 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=25)),
                ('lastName', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('companyName', models.CharField(max_length=250)),
                ('dateCreated', models.DateTimeField()),
                ('dateUpdated', models.DateTimeField()),
                ('salesContact_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salesTeam_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField()),
                ('dateUpdated', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('amount', models.FloatField()),
                ('paymentDue', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contract', to='customerRelationshipManagement_app.client')),
                ('salesContact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salesTeam_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField()),
                ('dateUpdated', models.DateTimeField()),
                ('attendees', models.IntegerField()),
                ('eventDate', models.DateTimeField()),
                ('notes', models.TextField(blank=True, max_length=2048)),
                ('eventStatus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_event', to='customerRelationshipManagement_app.contract')),
                ('supportContact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supportTeam_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
